spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15122878813/spring-cloud-study
          search-paths:
          - /configureFile #配置文件所在根目录
          default-label: master  #配置文件分支
          #无账号密码，因为为公共仓库
          username: 15122878813
          password: 100000qq6
  application:
    name: configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
---
server:
  port: 9005
spring:
  profiles: config1
---
server:
  port: 9006
spring:
  profiles: config2
