spring:
  application:
    name: provider
eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
