spring:
  zipkin:
    base-url: http://127.0.0.1:9411
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: consumer-feign
